


//creamos variableas array para cada departamento
var departamentos_AMAZONAS = ["Elegir","EL ENCANTO","LA CHORRERA","LA PEDRERA","LA VICTORIA","LETICIA","MIRITI-PARANA","PUERTO ALEGRIA","PUERTO ARICA","PUERTO NARIÑO","PUERTO SANTANDER","TARAPACA"];
var departamentos_ANTIOQUIA=["Elegir","CAUCASIA","EL BAGRE","NECHI","TARAZA","ZARAGOZA","CARACOLI","MACEO","PUERTO BERRIO","PUERTO NARE", 
"PUERTO TRIUNFO","YONDO","AMALFI","ANORI","CISNEROS","REMEDIOS","SAN ROQUE","SANTO DOMINGO","SEGOVIA","VEGACHI","YALI","YOLOMBO","ANGOSTURA","BELMIRA","BRICEÑO","CAMPAMENTO","CAROLINA DEL PRINCIPE","DONMATIAS","ENTRERRIOS","GOMEZ PLATA","GUADALUPE","ITUANGO" 
,"SAN ANDRES DE CUERQUIA","SAN JOSE DE LA MONTAÑA","SAN PEDRO DE LOS MILAGROS","SANTA ROSA DE OSOS","TOLEDO","VALDIVIA","YARUMAL","ABRIAQUI","ANZA","ARMENIA","BURITICA","CAICEDO","CAÑASGORDAS","DABEIBA","EBEJICO","FRONTINO","GIRALDO","HELICONIA","LIBORINA","OLAYA","PEQUE","SABANALARGA","SAN JERONIMO","SANTA FE DE ANTIOQUIA","SOPETRAN","URAMITA","ABEJORRAL","ALEJANDRIA","ARGELIA","CARMEN DE VIBORAL" 
,"COCORNA","CONCEPCION","GRANADA","GUARNE","GUATAPE","LA CEJA","LA UNION","MARINILLA","NARIÑO","EL PEÑOL","EL RETIRO","RIONEGRO","SAN CARLOS","SAN FRANCISCO","SAN LUIS","SAN RAFAEL","SAN VICENTE","SANTUARIO","SONSON","AMAGA","ANDES","ANGELOPOLIS","BETANIA","BOLIVAR","BETULIA","CARAMANTA","CONCORDIA","FREDONIA","HISPANIA","JARDIN","JERICO","LA PINTADA","MONTEBELLO","PUEBLORRICO","SALGAR","SANTA BARBARA","TAMESIS","TARSO","TITIRIBI","URRAO","VALPARAISO","VENECIA","APARTADO","ARBOLETES","CAREPA","CHIGORODO","MURINDO","MUTATA","NECOCLI","SAN JUAN DE URABA","SAN PEDRO DE URABA","TURBO","VIGIA DEL FUERTE","BARBOSA","BELLO","CALDAS","COPACABANA","ENVIGADO","GIRARDOTA","ITAGÜI" 
,"LA ESTRELLA","MEDELLIN","SABANETA"];
var departamentos_ARAUCA=["Elegir","ARAUCA","ARAUQUITA","CRAVO NORTE","FORTUL","PUERTO RONDON","SARAVENA","TAME"];
var departamentos_ATLANTICO=["Elegir","BARRANQUILLA","BARANOA","CAMPO DE LA CRUZ","CANDELARIA","GALAPA","JUAN DE ACOSTA","LURUACO","MALAMBO","MANATI","PALMAR DE VARELA","PIOJO","POLONUEVO","PONEDERA","PUERTO COLOMBIA","REPELON","SABANAGRANDE","SABANALARGA","SANTA LUCIA","SANTO TOMAS","SOLEDAD","SUAN","TUBARA","USIACURI"];
var departamentos_BOLIVAR=["Elegir","ACHI","ALTOS DEL ROSARIO","ARENAL","ARJONA","ARROYOHONDO","BARRANCO DE LOBA","BRAZUELO DE PAPAYAL"," CALAMAR","CANTAGALLO","EL CARMEN DE BOLIVAR","CARTAGENA DE INDIAS D.T.","CICUCO","CLEMENCIA","CORDOBA","EL GUAMO","EL PEÑON","HATILLO DE LOBA","MAGANGUE","MAHATES","MARGARITA","MARIA LA BAJA","MONTECRISTO","MORALES","NOROSI","PINILLOS","REGIDOR","RIO VIEJO","SAN CRISTOBAL", "SAN ESTANISLAO","SAN FERNANDO","SAN JACINTO","SAN JACINTO DEL CAUCASAN","JUAN NEPOMUCENO","SAN MARTIN DE LOBA","SAN PABLO","SANTA CATALINA","SANTA CRUZ DE MOMPOX","SANTA ROSA","SANTA ROSA DEL SUR","SIMITI","SOPLAVIENTO","TALAIGUA NUEVO","TIQUISIO","TURBACO","TURBANA","VILLANUEVA","ZAMBRANO"];
var departamentos_BOYACA=["Elegir","ALMEIDA","AQUITANIA","ARCABUCO","BELEN","BERBEO","BETEITIVA","BOAVITA","BOYACA","BRICEÑO","BUENAVISTA"," BUSBANZA","CALDAS","CAMPOHERMOSO","CERINZA","CHINAVITA","CHIQUINQUIRA","CHIQUIZA","CHISCAS","CHITA","CHITARAQUE","CHIVATA","CHIVOR"," CIENEGA","COMBITA","COPER","CORRALES","COVARACHIA","CUBARA","CUCAITA","CUITIVA","DUITAMA","EL COCUY","EL ESPINO","FIRAVITOBA","FLORESTA", "GACHANTIVA","GAMEZA","GARAGOA","GUACAMAYAS","GUATEQUE","GUAYATA","GÜICAN","IZA","JENESANO","JERICO","LA CAPILLA","LA UVITA","LA VICTORIA","LABRANZAGRANDE","MACANAL","MARIPI","MIRAFLORES","MONGUA","MONGUI","MONIQUIRA","MOTAVITA","MUZO","NOBSA","NUEVO COLON","OICATA","OTANCHE","PACHAVITA","PAEZ","PAIPA","PAJARITO","PANQUEBA","PAUNA","PAYA","PAZ DE RIO","PESCA","PISBA","PUERTO BOYACA","QUIPAMA","RAMIRIQUI","RAQUIRA","RONDON","SABOYA","SACHICA","SAMACA","SAN EDUARDO","SAN JOSE DE PARE","SAN LUIS DE GACENO","SAN MATEO","SAN MIGUEL DE SEMA"," SAN PABLO DE BORBUR","SANTA MARIA","SANTA ROSA DE VITERBO","SANTA SOFIA","SANTANA","SATIVANORTE","SATIVASUR","SIACHOQUE","SOATA","SOCHA","SOCOTA","SOGAMOSO","SOMONDOCO","SORA","SORACA","SOTAQUIRA","SUSACON","SUTAMARCHAN","SUTATENZA","TASCO","TENZA","TIBANA","TIBASOSA"," TINJACA","TIPACOQUE","TOCA","TOGÜI","TOPAGA","TOTA","TUNJA","TUNUNGUA","TURMEQUE","TUTA","TUTAZA","UMBITA","VENTAQUEMADA","VILLA DE LEYVA","VIRACACHA","ZETAQUIRA"];
var departamentos_CALDAS=["Elegir","AGUADAS","ANSERMA","ARANZAZU","BELALCAZAR","CHINCHINA","FILADELFIA","LA DORADA","LA MERCED","MANIZALES", "MANZANARES","MARMATO","MARQUETALIA","MARULANDA","NEIRA","NORCASIA","PACORA","PALESTINA","PENSILVANIA","RIOSUCIO","RISARALDA","SALAMINA", "SAMANA SAN JOSE","SUPIA","VICTORIA","VILLAMARIA","VITERBO"];
var departamentos_CAQUETA=["Elegir","ALBANIA","BELEN DE LOS ANDAQUIES","CARTAGENA DEL CHAIRA","CURILLO","EL DONCELLO","EL PAUJIL","FLORENCIA","LA MONTAÑITA","MORELIA","PUERTO MILAN","PUERTO RICO","SAN JOSE DEL FRAGUA","SAN VICENTE DEL CAGUAN","SOLANO","SOLITA","VALPARAISO"];
var departamentos_CASANARE=["Elegir","AGUAZUL","HATO COROZAL","CHAMEZA","PORE","LA SALINA","SACAMA","PAZ DE ARIPORO","MONTERREY","OROCUE","MANI","SAN LUIS DE PALENQUE","TRINIDAD","VILLANUEVA","YOPAL","RECETOR","SABANALARGA","TAMARA","NUNCHIA","TAURAMENA"];
var departamentos_CAUCA=["Elegir","ALMAGUER","ARGELIA","BALBOA","BOLIVAR","BUENOS AIRES","CAJIBIO","CALDONO","CALOTO","CORINTO","EL TAMBO",
"FLORENCIA","GUACHENE","GUAPI","INZA","JAMBALO","LA SIERRA","LA VEGA","LOPEZ DE MICAY","MERCADERES","MIRANDA","MORALES","PADILLA","PAEZ", "PATIA","PIAMONTE","PIENDAMO","POPAYAN","PUERTO TEJADA","PURACE","ROSAS","SAN SEBASTIAN","SANTA ROSA","SANTANDER DE QUILICHAO","SILVIA",
"SOTARA","SUAREZ","SUCRE","TIMBIO","TIMBIQUI","TORIBIO","TOTORO","VILLA RICA"];
var departamentos_CESAR=["Elegir","AGUACHICA","ASTREA","BECERRIL","BOSCONIA","CHIMICHAGUA","CHIRIGUANA","CODAZZI","CURUMANI","EL COPEY",
"EL PASO GAMARRA","GONZALEZ","LA GLORIA","LA JAGUA DE IBIRICO","LA PAZ","MANAURE","BALCON DEL CESAR","PAILITAS","PELAYA","PUEBLO BELLO",
"RIO DE ORO"," SAN ALBERTO"," SAN DIEGO"," SAN MARTIN"," TAMALAMEQUE"," VALLEDUPAR"];
var departamentos_CHOCO=["Elegir","ACANDI","ALTO BAUDO (PIE DE PATO];","ATRATO","BAGADO","BAHIA SOLANO","BAJO BAUDO (PIZARRO];","BOJAYA (BELLAVISTA];","CANTON DE SAN PABLO","EL CARMEN DE ATRATO","CERTEGUI","CONDOTO","EL CARMEN DEL DARIEN","ISTMINA","JURADO", 
"LITORAL DE SAN JUAN","LLORO","MEDIO ATRATO","MEDIO BAUDO","MEDIO SAN JUAN","NOVITA","NUQUI","QUIBDO","RIOSUCIO","RIO IRO","RIO QUITO", 
"SAN JOSE DEL PALMAR","SIPI","TADO","UNGUIA","UNION PANAMERICANA"];
var departamentos_CORDOBA=["Elegir","AYAPEL","BUENAVISTA","CANALETE","CERETE","CHIMA","CHINU","CIENAGA DE ORO","COTORRA","LA APARTADA","LOS CORDOBAS","MOMIL","MOÑITOS","MONTELIBANO","MONTERIA","PLANETA RICA","PUEBLO NUEVO","PUERTO ESCONDIDO","PUERTO LIBERTADOR","PURISIMA"," SAHAGUN","SAN ANDRES DE SOTAVENTO","SAN ANTERO","SAN BERNARDO DEL VIENTO","SAN CARLOS","SAN JOSE DE URE","SAN PELAYO","SANTA CRUZ DE LORICA","TIERRALTA","TUCHIN","VALENCIA"];
var departamentos_CUNDINAMARCA=["Elegir","AGUA DE DIOS","ALBA","ANAPOIMA","ANOLAIMA","APULO","ARBELAEZ","BELTRAN","BITUIMA","BOJACA", 
"CABRERA","CACHIPAY","CAJICA","CAPARRAPI","CAQUEZA","CARMEN DE CARUPA","CHAGUANI","CHIA","CHIPAQUE","CHOACHI","CHOCONTA","COGUA", 
"COTA","CUCUNUBA","EL COLEGIO","EL PEÑON","EL ROSAL","FACATATIVA","FOMEQUE","FOSCA","FUNZA","FUQUENE","FUSAGASUGA","GACHALA","GACHANCIPA","GACHETA","GAMA","GIRARDOT","GRANADA","GUACHETA","GUADUAS","GUASCA","GUATAQUI","GUATAVITA","GUAYABAL DE SIQUIMA","GUAYABETAL","GUTIERREZ","JERUSALEN","JUNIN","LA CALERA","LA MESA","LA PALMA","LA PEÑA","LA VEGA","LENGUAZAQUE","MACHETA","MADRID","MANTA","MEDINA","MOSQUERA", "NARIÑO","NEMOCON","NILO","NIMAIMA","NOCAIMA","PACHO","PAIME","PANDI","PARATEBUENO","PASCA","PUERTO SALGAR","PULI","QUEBRADANEGRA","QUETAME","QUIPILE","RICAURTE","SAN ANTONIO DEL TEQUENDAMA","SAN BERNARDO","SAN CAYETANO","SAN FRANCISCO","SAN JUAN DE RIOSECO","SASAIMA","SESQUILE","SIBATE","SILVANIA","SIMIJACA","SOACHA","SOPO","SUBACHOQUE","SUESCA","SUPATA","SUSA","SUTATAUSA","TABIO","TAUSA","TENA","TENJO","TIBACUY","TIBIRITA","TOCAIMA","TOCANCIPA","TOPAIPI","UBALA","UBAQUE","UBATE","UNE","UTICA","VENECIA","VERGARA","VIANI","VILLAGOMEZ"," VILLAPINZON","VILLETA","VIOTA","YACOPI","ZIPACON","ZIPAQUIRA"];
var departamentos_DISTRITO_CAPITAL=["Elegir","BOGOTA"];
var departamentos_GUAINIA=["Elegir","BARRANCO MINAS","CACAHUAL","INIRIDA","LA GUADALUPE","MAPIRIPANA","MORICHAL","PANA PANA","PUERTO COLOMBIA","SAN FELIPE"];
var departamentos_GUAJIRA=["Elegir","ALBANIA","BARRANCAS","DIBULLA","DISTRACCION","EL MOLINO","FONSECA","HATONUEVO","LA JAGUA DEL PILAR"," MAICAO","MANAURE","RIOHACHA","SAN JUAN DEL CESAR","URIBIA","URUMITA","VILLANUEVA"];
var departamentos_GUAVIARE=["Elegir","CALAMAR","EL RETORNO","MIRAFLORES","SAN JOSE DEL GUAVIARE"];
var departamentos_HUILA=["Elegir","ACEVEDO","AGRADO","AIPE","ALGECIRAS","ALTAMIRA","BARAYA","CAMPOALEGRE","COLOMBIA","ELIAS","GARZON"," GIGANTE","GUADALUPE","HOBO","IQUIRA","ISNOS","LA ARGENTINA","LA PLATA","NATAGA","NEIVA","OPORAPA","PAICOL","PALERMO","PALESTINA","PITAL","PITALITO","RIVERA","SALADOBLANCO","SAN AGUSTIN","SANTA MARIA","SUAZA","TARQUI","TELLO","TERUEL","TESALIA","TIMANA","VILLAVIEJA","YAGUARA"];
var departamentos_MAGDALENA=["Elegir","ALGARROBO","ARACATACA","ARIGUANI","CERRO DE SAN ANTONIO","CHIBOLO","CIENAGA","CONCORDIA","EL BANCO",
"EL PIÑON","EL RETEN","FUNDACION","GUAMAL","NUEVA GRANADA","PEDRAZA","PIJIÑO DEL CARMEN","PIVIJAY","PLATO","PUEBLO VIEJO","REMOLINO","SABANAS DE SAN ANGEL","SALAMINA","SAN SEBASTIAN DE BUENAVISTA","SANTA ANA","SANTA BARBARA DE PINTO","SANTA MARTA","SAN ZENON",
"SITIONUEVO","TENERIFE","ZAPAYAN","ZONA BANANERA"];
var departamentos_META=["Elegir","ACACIAS","BARRANCA DE UPIA","CABUYARO","CASTILLA LA NUEVA","CUBARRAL","CUMARAL","EL CALVARIO","EL CASTILLO","EL DORADO","FUENTE DE ORO","GRANADA","GUAMAL","LA MACARENA","LA URIBE","LEJANIAS","MAPIRIPAN","MESETAS","PUERTO CONCORDIA","PUERTO GAITAN","PUERTO LLERAS","PUERTO LOPEZ","PUERTO RICO","RESTREPO","SAN CARLOS DE GUAROA","SAN JUAN DE ARAMA","SAN JUANITO","SAN MARTIN", 
"VILLAVICENCIO","VISTA HERMOSA"];
var departamentos_NARINO=["Elegir","ALDANA","ANCUYA","ARBOLEDA (BERRUECOS];","BARBACOAS","BELEN","BUESACO","CHACHAGÜI","COLON (GENOVA];", 
"CONSACA","CONTADERO","CORDOBA","CUASPUD (CARLOSAMA];","CUMBAL","CUMBITARA","EL CHARCO","EL PEÑOL","EL ROSARIO","EL TABLON DE GOMEZ", 
"EL TAMBO","FRANCISCO PIZARRO (SALAHONDA];","FUNES","GUACHUCAL","GUAITARILLA","GUALMATAN","ILES","IMUES","IPIALES","LA CRUZ","LA FLORIDA", 
"LA LLANADA","LA TOLA","LA UNION","LEIVA","LINARES","LOS ANDES","MAGÜI (PAYAN];","MALLAMA (PIEDRANCHA];","MOSQUERA","NARIÑO", 
"OLAYA HERRERA (BOCAS DE SATINGA];","OSPINA","POLICARPA","POTOSI","PROVIDENCIA","PUERRES","PUPIALES","RICAURTE","ROBERTO PAYAN (SAN JOSE];","SAMANIEGO","SAN BERNARDO","SAN JOSE DE ALBAN","SAN JUAN DE PASTO","SAN LORENZO","SAN PABLO","SAN PEDRO DE CARTAGO","SANDONA","SANTA BARBARA (ISCUANDE];","SANTACRUZ (GUACHAVEZ];","SAPUYES","TAMINANGO","TANGUA","TUMACO","TUQUERRES","YACUANQUER"];
var departamentos_NORTE_DE_SANTANDER=["Elegir","ABREGO","ARBOLEDAS","BOCHALEMA","BUCARASICA","CACHIRA","CACOTA","CHINACOTA","CHITAGA","CONVENCION","CUCUTA","CUCUTILLA","DURANIA","EL CARMEN","EL TARRA","EL ZULIA","GRAMALOTE","HACARI","HERRAN","LA ESPERANZA","LA PLAYA DE BELEN","LABATECA","LOS PATIOS","LOURDES","MUTISCUA","OCAÑA","PAMPLONA","PAMPLONITA","PUERTO SANTANDER","RAGONVALIA",
"SALAZAR DE LAS PALMAS","SAN CALIXTO","SAN CAYETANO","SANTIAGO","SANTO DOMINGO DE SILOS","SARDINATA","TEORAMA","TIBU","TOLEDO", 
"VILLA CARO","VILLA DEL ROSARIO"];
var departamentos_PUTUMAYO=["Elegir","COLON","MOCOA","ORITO","PUERTO ASIS","PUERTO CAICEDO","PUERTO GUZMAN","PUERTO LEGUIZAMO","SAN FRANCISCO","SAN MIGUEL","SANTIAGO","SIBUNDOY","VALLE DEL GUAMEZ","VILLA GARZON"];
var departamentos_QUINDIO=["Elegir","ARMENIA","BUENAVISTA","CALARCA","CIRCASIA","CORDOBA","FILANDIA","GENOVA","LA TEBAIDA","MONTENEGRO", 
"PIJAO","QUIMBAYA","SALENTO"];
var departamentos_RISARALDA=["Elegir","APIA","BALBOA","BELEN DE UMBRIA","DOSQUEBRADAS","GUATICA","LA CELIA","LA VIRGINIA","MARSELLA", 
"MISTRATO","PEREIRA","PUEBLO RICO","QUINCHIA","SANTA ROSA DE CABAL","SANTUARIO"];
var departamentos_SAN_ANDRES=["Elegir","PROVIDENCIA","SAN ANDRES","SANTA CATALINA"];
var departamentos_SANTANDER=["Elegir","AGUADA","ALBANIA","ARATOCA","BARBOSA","BARICHARA","BARRANCABERMEJA","BETULIA","BOLIVAR","BUCARAMANGA","CABRERA","CALIFORNIA","CAPITANEJO","CARCASI","CEPITA","CERRITO","CHARALA","CHARTA","CHIMA","CHIPATA","CIMITARRA","CONCEPCION","CONFINES","CONTRATACION","COROMORO","CURITI","EL CARMEN DE CHUCURI","EL GUACAMAYO","EL PEÑON","EL PLAYON","ENCINO","ENCISO","FLORIAN","FLORIDABLANCA","GALAN","GAMBITA","GIRON","GUACA","GUADALUPE","GUAPOTA","GUAVATA","GÜEPSA","HATO","JESUS MARIA","JORDAN","LA BELLEZA","LA PAZ","LANDAZURI","LEBRIJA","LOS SANTOS","MACARAVITA","MALAGA","MATANZA","MOGOTES","MOLAGAVITA","OCAMONTE","OIBA","ONZAGA","PALMAR",
"PALMAS DEL SOCORRO","PARAMO","PIEDECUESTA","PINCHOTE","PUENTE NACIONAL","PUERTO PARRA","PUERTO WILCHES","RIONEGRO","SABANA DE TORRES",
"SAN ANDRES","SAN BENITO","SAN GIL","SAN JOAQUIN","SAN JOSE DE MIRANDA","SAN MIGUEL","SAN VICENTE","SANTA BARBARA",
"SANTA HELENA DEL OPON","SIMACOTA","SOCORRO","SUAITA","SUCRE","SURATA","TONA","VALLE DE SAN JOSE","VELEZ","VETAS","VILLANUEVA","ZAPATOCA"];
var departamentos_SUCRE=["Elegir","BUENAVISTA","CAIMITO","CHALAN","COLOSO","COROZAL","COVEÑAS","EL ROBLE","GALERAS","GUARANDA","LA UNION", 
"LOS PALMITOS","MAJAGUAL","MORROA","OVEJAS","PALMITO","SAMPUES","SAN BENITO ABAD","SAN JUAN DE BETULIA","SAN MARCOS","SAN ONOFRE", 
"SAN PEDRO","SANTIAGO DE TOLU","SINCE","SINCELEJO","SUCRE","TOLUVIEJO"];
var departamentos_TOLIMA=["Elegir","ALPUJARRA","ALVARADO","AMBALEMA","ANZOÁTEGUI","ARMERO","ATACO","CAJAMARCA","CARMEN DE APICALÁ", 
"CASABIANCA","CHAPARRAL","COELLO","COYAIMA","CUNDAY","DOLORES","ESPINAL","FALAN","FLANDES","FRESNO","GUAMO","HERVEO", 
"HONDA","IBAGUE","ICONONZO","LERIDA","LIBANO","MARIQUITA","MELGAR","MURILLO","NATAGAIMA","ORTEGA","PALOCABILDO","PIEDRAS", 
"PLANADAS","PRADO","PURIFICACION","RIOBLANCO","RONCESVALLES","ROVIRA","SALDAÑA","SAN ANTONIO","SAN LUIS","SANTA ISABEL", 
"SUAREZ","VALLE DE SAN JUAN","VENADILLO","VILLAHERMOSA","VILLARRICA"];
var departamentos_VALLE_DEL_CAUCA=["Elegir","ALCALA","ANDALUCIA","ANSERMANUEVO","ARGELIA","BOLIVAR","BUENAVENTURA","BUGA", 
"BUGALAGRANDE","CAICEDONIA","CALI","CANDELARIA","CARTAGO","DAGUA","DARIEN","EL AGUILA","EL CAIRO","EL CERRITO","EL DOVIO", 
"FLORIDA","GINEBRA","GUACARI","JAMUNDI","LA CUMBRE","LA UNION","LA VICTORIA","OBANDO","PALMIRA","PRADERA","RESTREPO", 
"RIOFRIO","ROLDANILLO","SAN PEDRO","SEVILLA","TORO","TRUJILLO","TULUA","ULLOA","VERSALLES","VIJES","YOTOCO","YUMBO","ZARZAL"];
var departamentos_VAUPES=["Elegir","CARURU","MITU","PACOA","PAPUNAUA","TARAIRA","YAVARATE"];
var departamentos_VICHADA=["Elegir","CUMARIBO","LA PRIMAVERA","PUERTO CARREÑO","SANTA ROSALIA"];


function cambia_departamento(){
 //tomamos el valor del select departamento elegido
 var dpt
 dpt = document.getElementById('departamentos').value	
     mis_dptos = acentos(dpt)
     // verificamos si el Departamento está definido

if (mis_dptos!=0) { 
      	 //si estaba definido, entonces coloco las opciones del Departamento correspondiente. 
      	 //selecciono el array del departamento adecuado 
      	 mis_municipios=eval("departamentos_"+mis_dptos) 
      	  //calculo el numero de municipios 
      	 num_municipios = mis_municipios.length 
      	 //marco el número de municipios en el select 
      	 document.f1.minucipios.length = num_municipios 
      	 //para cada municipio del array, lo introduzco en el select 
      	 for(i=0;i<num_municipios;i++){ 
         	 document.f1.minucipios.options[i].value=mis_municipios[i] 
         	 document.f1.minucipios.options[i].text=mis_municipios[i] 
      	 }	
   	    }else{ 
      	 //si no había municipio seleccionado, elimino los municipios del select 
      	 document.f1.minucipios.length = 1 
      	 //coloco un guión en la única opción que he dejado 
      	 document.f1.minucipios.options[0].value = " " 
      	 document.f1.minucipios.options[0].text = "SIN ASIGNAR" 
   	   } 
   	}// FIN DE FUNCIONcambia_departamento

   function acentos(dpt){
   var acentuada
   if(dpt=="ATLÁNTICO"){ acentuada="ATLANTICO";}
   else{
   	if(dpt=="BOLÍVAR"){ acentuada="BOLIVAR"; }
   	else{
   		if(dpt=="CAQUETÁ"){ acentuada="CAQUETA"; }
   		else{
   			if(dpt=="CHOCÓ"){ acentuada="CHOCO"; }
   			else{

   				if(dpt=="CÓRDOBA"){ acentuada="CORDOBA"; }
   				else{
   					if(dpt=="DISTRITO CAPITAL"){ acentuada="DISTRITO_CAPITAL"; }
   					else{
   						if(dpt=="GUAINÍA"){ acentuada="GUAINIA"; }
   						else{
   							if(dpt=="LA GUAJIRA"){ acentuada="GUAJIRA"; }
   							else{
   								if(dpt=="NARIÑO"){ acentuada="NARINO"; }
   								else{
   									if(dpt=="NORTE DE SANTANDER"){ acentuada="NORTE_DE_SANTANDER"; }
   									else{
   									if(dpt=="QUINDÍO"){ acentuada="QUINDIO"; }
   									else{
   										if(dpt=="SAN ANDRÉS Y PROVIDENCIA"){ acentuada="SAN_ANDRES"; }
   										else{
   											if(dpt=="VALLE DEL CAUCA"){ acentuada="VALLE_DEL_CAUCA"; }
   											else{
                                               if(dpt=="VAUPÉS"){ acentuada="VAUPES"; }
                                               else{
                                               	  acentuada=dpt;
                                               }
   											}
   										}
   									}	
   									}
   								}
   							}
   						}
   					}
   				}
   			}
   		}
   	}
   }
   	
   		
return  acentuada

   }// fin funcion acentos

   